version: '3.7'

services:
  # MONGO
  mongo:
    container_name: mongo
    hostname: mongo
    command: --quiet
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - webnetwork

  # BACK
  back:
    container_name: back
    hostname: back
    build: .
    volumes:
      - .:/app
      # - /app/node_modules
    ports:
      - 8080:8080
    restart: always
    env_file:
      - .env.development
    networks:
      - webnetwork
    depends_on:
      - mongo

networks:
  webnetwork:
